type: lamp
php: 8.4
database: mariadb:11.4
assets:
  - drupal-example.sql.gz

steps:
  - name: Install Drupal Based On Composer File
    plugin: Drupal
    drupalVersion: 11
    database: drupal-example.sql.gz
    databaseGzipped: true
    compsoer: true
    redis: true
    clearCaches: false
    databaseUpdates: false
    subDirectory: web
    
  - name: Run database update
    command: "drush --root=$SRC_DIR/docroot/ updb -y"
  #- name: Sanitize database
  #  command: "drush --root=$SRC_DIR/docroot/ sqlsan -y"
  ##- name: Import config
  ##  command: "drush --root=$SRC_DIR/docroot/ cim --source=$SRC_DIR/config/default -y"
  - name: Fix file permissions
    command: 'mkdir $SRC_DIR/docroot/sites/default/files/private && chown -R www-data:www-data $SRC_DIR/docroot/sites/default/files'
  #- name: Enable stage file proxy
  #  command: "drush --root=$SRC_DIR/docroot/ en stage_file_proxy -y && drush --root=$SRC_DIR/docroot/ cset stage_file_proxy.settings origin https://example.com -y"
  - name: Cache clear
    command: "drush --root=$SRC_DIR/docroot/ cr"