type: lamp
php: 8.4
database: mariadb:11.4

# The sample database can be obtained at:
# https://probosupportfiles.blob.core.windows.net/utils/drupal-example.sql.gz
assets:
  - drupal-example.sql.gz

steps:
  - name: Install Drupal Based On Composer File
    plugin: Drupal
    drupalVersion: 11
    database: drupal-example.sql.gz
    databaseGzipped: true
    composer: true
    redis: true
    clearCaches: false
    databaseUpdates: false
    subDirectory: web
    configSyncDirectory: ../config/sync
    
  - name: Run database update
    command: "drush --root=/var/www/html updb -y"

  - name: Import config
    command: "drush --root=/var/www/html cim -y"
  
  - name: Fix file permissions
    command: 'mkdir $SRC_DIR/web/sites/default/files/private && chown -R www-data:www-data $SRC_DIR/web/sites/default/files'
  
  - name: Cache clear
    command: "drush --root=/var/www/html cr"